/**
 * Copyright (c)2005-2009 Matt Kruse (javascripttoolbox.com)
 * 
 * Dual licensed under the MIT and GPL licenses. 
 * This basically means you can use this code however you want for
 * free, but don't claim to have written it yourself!
 * Donations always accepted: http://www.JavascriptToolbox.com/donate/
 * 
 * Please do not link to the .js files on javascripttoolbox.com from
 * your site. Copy the files locally to your server instead.
 * 
 */

define([],function(){Date.$VERSION=1.02,Date.LZ=function(a){return(a<0||a>9?"":"0")+a},Date.monthNames=new Array("January","February","March","April","May","June","July","August","September","October","November","December"),Date.monthAbbreviations=new Array("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"),Date.dayNames=new Array("Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"),Date.dayAbbreviations=new Array("Sun","Mon","Tue","Wed","Thu","Fri","Sat"),Date.preferAmericanFormat=!0,Date.prototype.getFullYear||(Date.prototype.getFullYear=function(){var a=this.getYear();return a<1900?a+1900:a}),Date.parseString=function(a,b){if(typeof b=="undefined"||b==null||b==""){var c=new Array("y-M-d","MMM d, y","MMM d,y","y-MMM-d","d-MMM-y","MMM d","MMM-d","d-MMM"),d=new Array("M/d/y","M-d-y","M.d.y","M/d","M-d"),e=new Array("d/M/y","d-M-y","d.M.y","d/M","d-M"),f=new Array(c,Date.preferAmericanFormat?d:e,Date.preferAmericanFormat?e:d);for(var g=0;g<f.length
;g++){var h=f[g];for(var i=0;i<h.length;i++){var j=Date.parseString(a,h[i]);if(j!=null)return j}}return null}this.isInteger=function(a){for(var b=0;b<a.length;b++)if("1234567890".indexOf(a.charAt(b))==-1)return!1;return!0},this.getInt=function(a,b,c,d){for(var e=d;e>=c;e--){var f=a.substring(b,b+e);if(f.length<c)return null;if(this.isInteger(f))return f}return null},a+="",b+="";var k=0,l=0,m="",n="",o="",p,q,r=(new Date).getFullYear(),s=1,t=1,u=0,v=0,w=0,x="";while(l<b.length){m=b.charAt(l),n="";while(b.charAt(l)==m&&l<b.length)n+=b.charAt(l++);if(n=="yyyy"||n=="yy"||n=="y"){n=="yyyy"&&(p=4,q=4),n=="yy"&&(p=2,q=2),n=="y"&&(p=2,q=4),r=this.getInt(a,k,p,q);if(r==null)return null;k+=r.length,r.length==2&&(r>70?r=1900+(r-0):r=2e3+(r-0))}else if(n=="MMM"||n=="NNN"){s=0;var y=n=="MMM"?Date.monthNames.concat(Date.monthAbbreviations):Date.monthAbbreviations;for(var g=0;g<y.length;g++){var z=y[g];if(a.substring(k,k+z.length).toLowerCase()==z.toLowerCase()){s=g%12+1,k+=z.length;break}}if(s<1||s>12
)return null}else if(n=="EE"||n=="E"){var y=n=="EE"?Date.dayNames:Date.dayAbbreviations;for(var g=0;g<y.length;g++){var A=y[g];if(a.substring(k,k+A.length).toLowerCase()==A.toLowerCase()){k+=A.length;break}}}else if(n=="MM"||n=="M"){s=this.getInt(a,k,n.length,2);if(s==null||s<1||s>12)return null;k+=s.length}else if(n=="dd"||n=="d"){t=this.getInt(a,k,n.length,2);if(t==null||t<1||t>31)return null;k+=t.length}else if(n=="hh"||n=="h"){u=this.getInt(a,k,n.length,2);if(u==null||u<1||u>12)return null;k+=u.length}else if(n=="HH"||n=="H"){u=this.getInt(a,k,n.length,2);if(u==null||u<0||u>23)return null;k+=u.length}else if(n=="KK"||n=="K"){u=this.getInt(a,k,n.length,2);if(u==null||u<0||u>11)return null;k+=u.length,u++}else if(n=="kk"||n=="k"){u=this.getInt(a,k,n.length,2);if(u==null||u<1||u>24)return null;k+=u.length,u--}else if(n=="mm"||n=="m"){v=this.getInt(a,k,n.length,2);if(v==null||v<0||v>59)return null;k+=v.length}else if(n=="ss"||n=="s"){w=this.getInt(a,k,n.length,2);if(w==null||w<0||w>59)return null
;k+=w.length}else if(n=="a"){if(a.substring(k,k+2).toLowerCase()=="am")x="AM";else{if(a.substring(k,k+2).toLowerCase()!="pm")return null;x="PM"}k+=2}else{if(a.substring(k,k+n.length)!=n)return null;k+=n.length}}if(k!=a.length)return null;if(s==2)if(r%4==0&&r%100!=0||r%400==0){if(t>29)return null}else if(t>28)return null;if(s==4||s==6||s==9||s==11)if(t>30)return null;return u<12&&x=="PM"?u=u-0+12:u>11&&x=="AM"&&(u-=12),new Date(r,s-1,t,u,v,w)},Date.isValid=function(a,b){return Date.parseString(a,b)!=null},Date.prototype.isBefore=function(a){return a==null?!1:this.getTime()<a.getTime()},Date.prototype.isAfter=function(a){return a==null?!1:this.getTime()>a.getTime()},Date.prototype.equals=function(a){return a==null?!1:this.getTime()==a.getTime()},Date.prototype.equalsIgnoreTime=function(a){if(a==null)return!1;var b=(new Date(this.getTime())).clearTime(),c=(new Date(a.getTime())).clearTime();return b.getTime()==c.getTime()},Date.prototype.format=function(a){a+="";var b="",c=0,d="",e="",f=this
.getYear()+"",g=this.getMonth()+1,h=this.getDate(),i=this.getDay(),j=this.getHours(),k=this.getMinutes(),l=this.getSeconds(),m,n,o,p,q,r,s,t,u,v,w,j,x,y,z,A,B=new Object;f.length<4&&(f=""+(+f+1900)),B.y=""+f,B.yyyy=f,B.yy=f.substring(2,4),B.M=g,B.MM=Date.LZ(g),B.MMM=Date.monthNames[g-1],B.NNN=Date.monthAbbreviations[g-1],B.d=h,B.dd=Date.LZ(h),B.E=Date.dayAbbreviations[i],B.EE=Date.dayNames[i],B.H=j,B.HH=Date.LZ(j),j==0?B.h=12:j>12?B.h=j-12:B.h=j,B.hh=Date.LZ(B.h),B.K=B.h-1,B.k=B.H+1,B.KK=Date.LZ(B.K),B.kk=Date.LZ(B.k),j>11?B.a="PM":B.a="AM",B.m=k,B.mm=Date.LZ(k),B.s=l,B.ss=Date.LZ(l);while(c<a.length){d=a.charAt(c),e="";while(a.charAt(c)==d&&c<a.length)e+=a.charAt(c++);typeof B[e]!="undefined"?b+=B[e]:b+=e}return b},Date.prototype.getDayName=function(){return Date.dayNames[this.getDay()]},Date.prototype.getDayAbbreviation=function(){return Date.dayAbbreviations[this.getDay()]},Date.prototype.getMonthName=function(){return Date.monthNames[this.getMonth()]},Date.prototype.getMonthAbbreviation=
function(){return Date.monthAbbreviations[this.getMonth()]},Date.prototype.clearTime=function(){return this.setHours(0),this.setMinutes(0),this.setSeconds(0),this.setMilliseconds(0),this},Date.prototype.add=function(a,b){if(typeof a=="undefined"||a==null||typeof b=="undefined"||b==null)return this;b=+b;if(a=="y")this.setFullYear(this.getFullYear()+b);else if(a=="M")this.setMonth(this.getMonth()+b);else if(a=="d")this.setDate(this.getDate()+b);else if(a=="w"){var c=b>0?1:-1;while(b!=0){this.add("d",c);while(this.getDay()==0||this.getDay()==6)this.add("d",c);b-=c}}else a=="h"?this.setHours(this.getHours()+b):a=="m"?this.setMinutes(this.getMinutes()+b):a=="s"&&this.setSeconds(this.getSeconds()+b);return this}})